server:
  port: 8080

spring:
  application:
    name: yongjibus
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    tags-sorter: alpha  # 태그 알파벳 순 정렬
    operations-sorter: method  # HTTP 메소드 기준 정렬
  api-docs:
    path: /api-docs/json
  show-actuator: false  # Actuator 엔드포인트 표시 여부
  default-produces-media-type: application/json